# ---------------------------------
# package sources for this program:
# ---------------------------------

AMRLIB:=$(CLAW)/amrclaw/src/2d
ADJLIB:=$(CLAW)/amrclaw/src/2d/adjoint
include $(AMRLIB)/Makefile.amr_2d

#list of common sources needed for adjoint code
MODULES += \

# list of source files from ADJLIB library. 
SOURCES += \
  $(ADJLIB)/errf1.f \
  $(ADJLIB)/errest.f \
